nav:
  - index.md
  - Built-in Toolsets: builtin-toolsets
  - Custom Toolsets: custom-toolsets.md
  - Remote MCP Servers: remote-mcp-servers.md
  - Adding Permissions for Additional Resources: permissions.md
