#model: "gpt-4o"
#api_key: "..."

#model: "azure/model-deployment-name"
#api_key: "..."

# try adding your own tools here!
# e.g. query company-specific data, fetch logs from your existing observability tools, etc
#custom_toolsets: ["examples/custom_toolset.yaml"]

#alertmanager_url: "http://localhost:9093"

#jira_username: "user@company.com"
#jira_api_key: "..."
#jira_url: "https://your-company.atlassian.net"
#jira_query: "project = 'Natan Test Project' and Status = 'To Do'"

#slack_token: "..."
#slack_channel: "#general"

#github_owner: "robusta-dev"
#github_pat: "..."
#github_url: "https://api.github.com" (default)
#github_repository: "holmesgpt"
#github_query: "is:issue is:open"

# give the LLM explicit instructions how to investigate certain alerts
# try adding runbooks to get better results on known alerts
#custom_runbooks: ["examples/custom_runbooks.yaml"]

# Azure Monitor toolsets configuration (for AKS cluster monitoring)
# Both toolsets are enabled by default and auto-detect configuration when running in AKS
#toolsets:
#  azuremonitormetrics:
#    auto_detect_cluster: true  # Default: auto-detect AKS cluster and Azure Monitor workspace
#    cache_duration_seconds: 1800  # Cache duration for Azure API calls (30 minutes)
#    # Manual configuration (optional, for explicit setup):
#    #azure_monitor_workspace_endpoint: "https://your-workspace.prometheus.monitor.azure.com/"
#    #cluster_name: "your-aks-cluster-name"
#    #cluster_resource_id: "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx"
#
#  azuremonitorlogs:
#    auto_detect_cluster: true  # Default: auto-detect AKS cluster and Container Insights
#    # Manual configuration (optional, for explicit setup):
#    #cluster_name: "your-aks-cluster-name"
#    #cluster_resource_id: "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx"
#    #log_analytics_workspace_id: "12345678-1234-1234-1234-123456789012"
#    #log_analytics_workspace_resource_id: "/subscriptions/xxx/resourcegroups/xxx/providers/microsoft.operationalinsights/workspaces/xxx"
