#model: "gpt-4o"
#api_key: "..."

#model: "azure/model-deployment-name"
#api_key: "..."

# try adding your own tools here!
# e.g. query company-specific data, fetch logs from your existing observability tools, etc
#custom_toolsets: ["examples/custom_toolset.yaml"]

#alertmanager_url: "http://localhost:9093"

#jira_username: "user@company.com"
#jira_api_key: "..."
#jira_url: "https://your-company.atlassian.net"
#jira_query: "project = 'Natan Test Project' and Status = 'To Do'"

#slack_token: "..."
#slack_channel: "#general"

#github_owner: "robusta-dev"
#github_pat: "..."
#github_url: "https://api.github.com" (default)
#github_repository: "holmesgpt"
#github_query: "is:issue is:open"

# give the LLM explicit instructions how to investigate certain alerts
# try adding runbooks to get better results on known alerts
#custom_runbooks: ["examples/custom_runbooks.yaml"]
