site_name: HolmesGPT Documentation
site_description: AI-powered root cause analysis for DevOps and SRE teams
site_url: https://holmesgpt.dev/
repo_url: https://github.com/robusta-dev/holmesgpt
repo_name: robusta-dev/holmesgpt
edit_uri: edit/master/docs/
exclude_docs: |
  _*
  snippets/
  README.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: Fira Code
  favicon: assets/favicon.png
  logo: assets/logo.png

plugins:
  - awesome-nav
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  # - git-committers:
  #     repository: robusta-dev/holmesgpt
  #     branch: master
  #     docs_path: docs/
  # - minify:
  #     minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: robusta-dev
      repo: holmesgpt
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: yaml-helm-values
          class: yaml
          format: !!python/name:docs.custom_fences.helm_tabs_fence_format
        - name: yaml-toolset-config
          class: yaml
          format: !!python/name:docs.custom_fences.toolset_config_fence_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/robusta-dev/holmesgpt
    - icon: fontawesome/brands/slack
      link: https://bit.ly/robusta-slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RobustaDev
