{{- if .Values.operator.enabled }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healthchecks.holmes.robusta.dev
spec:
  group: holmes.robusta.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - query
            properties:
              query:
                type: string
                description: "The health check query to evaluate"
              timeout:
                type: integer
                description: "Timeout in seconds for check execution"
                default: 30
                minimum: 1
                maximum: 300
              mode:
                type: string
                description: "Execution mode: alert or monitor"
                enum:
                - alert
                - monitor
                default: monitor
              destinations:
                type: array
                description: "Alert destinations for failed checks"
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                      - slack
                      - pagerduty
                    config:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
              model:
                type: string
                description: "LLM model to use for this check (e.g., gpt-4.1, claude-sonnet-4-20250514)"
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            description: "Status of the health check execution"
            properties:
              phase:
                type: string
                description: "Current phase: Pending, Running, Completed"
                enum:
                - Pending
                - Running
                - Completed
              startTime:
                type: string
                format: date-time
                description: "Time when execution started"
              completionTime:
                type: string
                format: date-time
                description: "Time when execution completed"
              result:
                type: string
                description: "Result of execution: pass, fail, or error"
                enum:
                - pass
                - fail
                - error
              message:
                type: string
                description: "Message from execution"
              rationale:
                type: string
                description: "Detailed explanation of the result"
              duration:
                type: number
                description: "Execution duration in seconds"
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Result
      type: string
      description: "Execution result"
      jsonPath: .status.result
    - name: Duration
      type: number
      description: "Execution duration in seconds"
      jsonPath: .status.duration
    - name: Query
      type: string
      description: "Health check query (short)"
      jsonPath: .status.shortQuery
    - name: Message
      type: string
      description: "Result message (short)"
      jsonPath: .status.shortMessage
    - name: Model
      type: string
      description: "LLM model used"
      jsonPath: .spec.model
      priority: 0
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: healthchecks
    singular: healthcheck
    kind: HealthCheck
    shortNames:
    - hc
{{- end }}
