nav:
  - index.md
  - AKS Node Health: aks-node-health.md
  - ArgoCD: argocd.md
  - AWS: aws.md
  - Azure Kubernetes Service: aks.md
  - Azure SQL Database: azure-sql.md
  - Confluence: confluence.md
  - Coralogix logs: coralogix-logs.md
  - DataDog: datadog.md
  - Datetime: datetime.md
  - Docker: docker.md
  - GitHub: github.md
  - Loki: grafanaloki.md
  - Tempo: grafanatempo.md
  - Helm: helm.md
  - Internet: internet.md
  - Kafka: kafka.md
  - Kubernetes: kubernetes.md
  - MongoDB Atlas: mongodb-atlas.md
  - New Relic: newrelic.md
  - Notion: notion.md
  - OpenSearch logs: opensearch-logs.md
  - OpenSearch status: opensearch-status.md
  - Prometheus: prometheus.md
  - RabbitMQ: rabbitmq.md
  - Robusta: robusta.md
  - ServiceNow: servicenow.md
  - Slab: slab.md
